# Generated by Django 4.0.5 on 2022-06-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0002_wishgrantes_wish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='dateAdd',
        ),
        migrations.RemoveField(
            model_name='wishgrantes',
            name='dateAdd2',
        ),
        migrations.RemoveField(
            model_name='wishgrantes',
            name='dateGranted',
        ),
    ]
