# Generated by Django 4.0.5 on 2022-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0003_remove_wish_dateadd_remove_wishgrantes_dateadd2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='uploaded_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='wish',
            name='granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='granted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_wish', to='ExamApp.users'),
        ),
        migrations.DeleteModel(
            name='wishGrantes',
        ),
    ]
