# Generated by Django 4.0.5 on 2022-06-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0005_rename_wish_wishs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishs',
            name='granted_at',
            field=models.DateTimeField(auto_now=True, default='date'),
            preserve_default=False,
        ),
    ]
